"""create_pet_model

Revision ID: a0ee099d1775
Revises: 57b460a916d4
Create Date: 2022-08-31 09:42:59.085195

"""
from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy import guid


# revision identifiers, used by Alembic.
revision = 'a0ee099d1775'
down_revision = '57b460a916d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', guid.GUID(), nullable=True),
    sa.Column('pet_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
